// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_boolean = require("bs-platform/lib/js/js_boolean.js");

function encode(_, v) {
  return JSON.stringify(v[0]);
}

function string(v) {
  return /* Value */[v];
}

function $$int(v) {
  return /* Value */[v];
}

function $$float(v) {
  return /* Value */[v];
}

function bool(v) {
  return /* Value */[Js_boolean.to_js_boolean(v)];
}

var $$null = /* Value */[null];

function array(v) {
  var json_t_ar = $$Array.map((function (param) {
          return param[0];
        }), v);
  return /* Value */[json_t_ar];
}

function list(v) {
  return array($$Array.of_list(v));
}

function object$prime(v) {
  var deconstruct_pair = function (param) {
    return /* tuple */[
            param[0],
            param[1][0]
          ];
  };
  return /* Value */[Js_dict.fromList(List.map(deconstruct_pair, v))];
}

exports.encode = encode;
exports.string = string;
exports.$$int = $$int;
exports.$$float = $$float;
exports.bool = bool;
exports.$$null = $$null;
exports.array = array;
exports.list = list;
exports.object$prime = object$prime;
/* null Not a pure module */
