// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Jsonx_encode = require("../src/jsonx_encode.bs.js");

describe("Encode", (function () {
        describe("#encode", (function () {
                return Jest.test("encodes values to json string", (function () {
                              var got = Jsonx_encode.encode(0, Jsonx_encode.object$prime(/* :: */[
                                        /* tuple */[
                                          "name",
                                          Jsonx_encode.string("John Doe")
                                        ],
                                        /* :: */[
                                          /* tuple */[
                                            "age",
                                            Jsonx_encode.$$int(41)
                                          ],
                                          /* :: */[
                                            /* tuple */[
                                              "height",
                                              Jsonx_encode.$$float(183.4)
                                            ],
                                            /* :: */[
                                              /* tuple */[
                                                "has_hair",
                                                Jsonx_encode.bool(/* true */1)
                                              ],
                                              /* :: */[
                                                /* tuple */[
                                                  "parent_id",
                                                  Jsonx_encode.$$null
                                                ],
                                                /* :: */[
                                                  /* tuple */[
                                                    "pets",
                                                    Jsonx_encode.array(/* array */[
                                                          Jsonx_encode.string("fluffy"),
                                                          Jsonx_encode.string("zoomer"),
                                                          Jsonx_encode.string("oscar")
                                                        ])
                                                  ],
                                                  /* :: */[
                                                    /* tuple */[
                                                      "fav_colors",
                                                      Jsonx_encode.list(/* :: */[
                                                            Jsonx_encode.string("red"),
                                                            /* :: */[
                                                              Jsonx_encode.string("white"),
                                                              /* [] */0
                                                            ]
                                                          ])
                                                    ],
                                                    /* [] */0
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]));
                              return Jest.Expect[/* toEqual */12](got, Jest.Expect[/* expect */0]("{\"name\":\"John Doe\",\"age\":41,\"height\":183.4,\"has_hair\":true,\"parent_id\":null,\"pets\":[\"fluffy\",\"zoomer\",\"oscar\"],\"fav_colors\":[\"red\",\"white\"]}"));
                            }));
              }));
        return /* () */0;
      }));

/*  Not a pure module */
